name: "Run Client Tests"
description: "Run specific type of client tests"

inputs:
  test-type:
    description: "Type of test to run (unit, integration, ct, e2e)"
    required: true
  needs-playwright:
    description: "Whether Playwright browsers are needed"
    required: false
    default: "false"
  node-version:
    description: "Node.js version to use"
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup
      if: ${{ inputs.needs-playwright == 'false' }}
      uses: ./.github/actions/setup-deps
      with:
        node-version: ${{ inputs.node-version }}

    - name: Setup Playwright
      if: ${{ inputs.needs-playwright == 'true' }}
      uses: ./.github/actions/setup-playwright
      with:
        node-version: ${{ inputs.node-version }}

    - name: Run tests
      shell: bash
      run: |
        cd packages/client
        npm run test:${{ inputs.test-type }}
