name: "Setup Playwright"
description: "Setup Node.js, dependencies and install Playwright browsers"

inputs:
  node-version:
    description: "Node.js version to use"
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: ./.github/actions/setup-node
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install Playwright browsers
      shell: bash
      run: |
        cd packages/client
        npx playwright install --with-deps chromium
