name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup

      - name: Run ESLint
        run: npm run lint

  typecheck:
    name: TypeScript Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup

      - name: TypeScript check
        run: npm run typecheck

  build-client:
    name: Build Client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup

      - name: Build client
        run: npm run build --workspace=@music-app/client

  build-server:
    name: Build Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup

      - name: Build server
        run: npm run build --workspace=@music-app/server

  test-server:
    name: Server Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup

      - name: Run server tests
        run: npm run server:test

  test-client-unit:
    name: Client Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run unit tests
        uses: ./.github/actions/test-client
        with:
          test-type: unit

  test-client-integration:
    name: Client Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run integration tests
        uses: ./.github/actions/test-client
        with:
          test-type: integration

  test-client-component:
    name: Client Component Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run component tests
        uses: ./.github/actions/test-client
        with:
          test-type: ct
          needs-playwright: 'true'

  test-e2e:
    name: E2E Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run E2E tests
        uses: ./.github/actions/test-client
        with:
          test-type: e2e
          needs-playwright: "true"
